version: '3.5'

networks:
    default:
        driver: overlay
    frontend:
        driver: overlay
        attachable: true

volumes:
    portainer_data:

services:
    agent:
        image: portainer/agent:2.21.5
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
        networks:
            - default
        deploy:
            mode: global
            placement:
                constraints: [node.platform.os == linux]

    portainer:
        image: portainer/portainer-ce:2.21.5
        command: -H tcp://tasks.agent:9001 --tlsskipverify
        environment:
            - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
            - VIRTUAL_HOST=${VIRTUAL_HOST}
            - VIRTUAL_PORT=${VIRTUAL_PORT}
        volumes:
            - portainer_data:/data
        networks:
            - default
            - frontend
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]
